binary_sensor:
  - platform: status
    name: ${hostname} Status
    id: ${hostid}_status


sensor:
  - platform: uptime
    name: ${hostname} Uptime
    id: ${hostid}_uptime
    update_interval: 15s

  - platform: wifi_signal
    name: ${hostname} WiFi RSSI
    id: ${hostid}_wifi_rssi
    update_interval: 15s

  - platform: template
    name: ${hostname} WiFi Quality
    id: ${hostid}_wifi_quality
    icon: "mdi:wifi"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 15s
    lambda: |-
      // Taken from  https://github.com/tzapu/WiFiManager/blob/master/WiFiManager.cpp
      int quality;
      const int rssi = id(${hostid}_wifi_rssi).state;
      if (rssi <= -100) { quality = 0; }
      else if (rssi >= -50) { quality = 100; }
      else { quality = 2 * (rssi + 100); }
      return quality;

    # Requires https://github.com/ssieb/custom_components/tree/master/heapmon
  # - platform: heapmon
  #   id: ${hostid}_heapspace
  #   name: ${hostname} Free Space

  - platform: template
    name: ${hostname} WiFi Channel
    id: ${hostid}_wifi_channel
    lambda: return WiFi.channel();
    accuracy_decimals: 0
    update_interval: 60s


text_sensor:
  - platform: version
    id: ${hostid}_esphome_version
    name: ${hostname} ESPHome Version

  - platform: wifi_info
    ip_address:
      name: ${hostname} IP Address
      id: ${hostid}_ip_address
    ssid:
      name: ${hostname} Connected SSID
      id: ${hostid}_connected_ssid
    bssid:
      name: ${hostname} Connected BSSID
      id: ${hostid}_connected_bssid
    mac_address:
      name: ${hostname} MAC Address
      id: ${hostid}_mac_address


switch:
  - platform: restart
    name: ${hostname} Restart
    id: ${hostid}_restart

  - platform: shutdown
    name: ${hostname} Shutdown
    id: ${hostid}_shutdown
    

time:
  - platform: sntp
    id: sntp_time
  - platform: homeassistant
    id: ha_time
