# This workflow generates documentation (PDFs, interactive BOMs, board images). The
# The version number and date of the design is automatically updated in the schematic
# file and on the PCB. The version number is set via an environment variable
# and by default is `pre-release` since this runs outside of the release process
# so there's no formal release number to use.

# To use this workflow in your own repo you need to edit the environment variables in the env: section
# below.
name: "KiBot - Generate Schematic Outputs"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Design version"
        required: true
        default: "pre-release"


jobs:
  Documentation:
    env:
      # Set this to the base filename of your project.
      BaseFileName: circuits/driver-board
      # Set this to your local timezone. See https://www.wikiwand.com/en/List_of_tz_database_time_zones for valid strings.
      Timezone: Europe/Copenhagen
      # Set this to the output folder for all of the generated files. Unless you have a very
      # good reason to change this you should leave it as KiBotOutput.
      OutputFolder: exports
      # Set this to the version to include in the schematic and PCB. Since this
      # script runs outside of the release process it can't pull a version
      # number automatically from GitHub.
      Version: pre-release
    runs-on: ubuntu-latest

    # These are all the steps that generate the files.
    steps:
      # Check out the files
      - uses: actions/checkout@v3
        with:
          submodules: true

      # Get the current date and time, in the timezone specified above, for use later.
      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::$(TZ='${{ env.Timezone }}' date +'%Y-%m-%d %T')"

      # Get the current date
      - name: Get current date
        id: date_only
        run: echo "::set-output name=date_only::$(TZ='${{ env.Timezone }}' date +'%Y-%m-%d')"

      # Do a string replacement in the schematic file to set the version and date.
      # Any instance of %%version%% in the schematic gets replaced with the release version.
      # Any instance of %%date%% in the schematic gets replaced with the release date and time.
      - name: Set schematic version
        uses: jacobtomlinson/gha-find-replace@master
        with:
          include: ".*.kicad_sch"
          find: "%%version%%"
          replace: ${{ github.event.inputs.version }}

      - name: Set schematic date
        uses: jacobtomlinson/gha-find-replace@master
        with:
          include: ".*.kicad_sch"
          find: "%%date%%"
          replace: ${{ steps.date.outputs.date }}

      # Actually run KiBot to generate all the files. The KiBot script used is
      # in the .kibot/release.kibot.yaml folder.
      - name: Generate schematic documentation
        uses: INTI-CMNB/KiBot@v2_k6
        with:
          config: .kibot/sch-outputs.kibot.yaml
          dir: ${{ env.OutputFolder }}
          schema: ${{ env.BaseFileName }}.kicad_sch
          board: ${{ env.BaseFileName }}.kicad_pcb

      # Archive all the artifacts from output and attach to the action's results.
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BaseFileName }}-${{ github.event.inputs.version }}-${{ steps.date_only.outputs.date_only }}
          path: ${{ env.OutputFolder }}/**